import { Router } from 'express';
import authrouter from './authrouter.js';
import workspacesrouter from './workspacesrouter.js';
import workspacemembersrouter from './workspacemembersrouter.js';
import teamsrouter from './teamsrouter.js';
import teamMembers from './teamMembers.js';
import projectsrouter from './projectsrouter.js';
import projectTeamsrouter from './projectTeamsrouter.js';
import taskrouter from './tasksrouter.js';
const router = Router();
router.use(authrouter);
router.use(workspacesrouter);
router.use(workspacemembersrouter);
router.use(teamsrouter);
router.use(teamMembers);
router.use(projectsrouter);
router.use(projectTeamsrouter);
router.use(taskrouter);
export default router;
